s:
  env:
  - name: ENV_NAME
    value: main
  - name: ENV_DOMAIN
    value: s-27cdsx.forkmain.cloud
  fullnameOverride: s
  image:
    repository: ghcr.io/forkmain-bot/s
    tag: latest
  imagePullSecrets:
  - name: s-docker
  ingress:
    className: nginx
    enabled: true
    hosts:
    - host: s-27cdsx.forkmain.cloud
      paths:
      - path: /
        pathType: ImplementationSpecific
  nocalhost:
    command:
      debug:
      - yarn
      - install
      - '&&'
      - yarn
      - dev
      run:
      - yarn
      - install
      - '&&'
      - yarn
      - dev
    configPath: conf/nocalhost.yaml
    env: null
    gitURL: https://github.com/forkmain-bot/s.git
    hotReload: false
    image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/node:latest
    language: javascript
    patches: null
    persistentVolumeDirs:
    - capacity: 20Gi
      path: /home/nocalhost-dev
    remoteDebugPort: 9009
  service:
    port: 3000
    targetPort: 3000
